---
title: REMIR CESIT MPT
author: 
github: {user: timelyportfolio, repo: rCharts_nyt_home_price, branch: "gh-pages"}
framework: bootstrap
mode: selfcontained
widgets: "nyt_home"
highlighter: prettify
hitheme: twitter-bootstrap
assets:
  css:
    - "http://fonts.googleapis.com/css?family=Raleway:300"
    - "http://fonts.googleapis.com/css?family=Oxygen"
---

<style>
body{
  font-family: 'Oxygen', sans-serif;
  font-size: 16px;
  line-height: 24px;
}

h1,h2,h3,h4 {
  font-family: 'Raleway', sans-serif;
}

.container { width: 1000px; }
h3 {
  background-color: #D4DAEC;
  text-indent: 100px; 
}
h4 {
  text-indent: 100px;
}

g-table-intro h4 {
  text-indent: 0px;
}
</style>




---
<br/>

### Números gerais
  
  * <a href="https://arthurwelle.github.io/REMIR/PNADCT_Tx_Atividade.html"> PNADC Trimestral - Taxa de atividade (Sexo, Idade, Região, Raça/Cor) </a> 
  
  * <a href="https://arthurwelle.github.io/REMIR/R.PNADCT_TxDesocup.html"> PNADC Trimestral - Taxa de desocupação (Sexo, Idade, Região, Raça/Cor) </a>
  
  * <a href="https://arthurwelle.github.io/REMIR/R.PNADCMensal_TaxadeDesocupacao.html"> PNADC Mensal - Taxa de desocupação </a>
  
  * <a href="https://arthurwelle.github.io/REMIR/R.PNADCMensal_Conta_Propria.html"> PNADC Mensal - Conta-própria </a>
  
  * <a href="https://arthurwelle.github.io/REMIR/R.PNADCMensal_CondicaodeAtividade.html"> PNADC Mensal - Força de trabalho </a>
  
  * <a href="https://arthurwelle.github.io/REMIR/R.PNADCMensal_Grupamento_Atividades.html"> PNADC Mensal - Empregados por setor de atividade </a>
  
  * <a href="https://arthurwelle.github.io/REMIR/R.PNADCMensal_Subutilizacao.html"> PNADC Mensal - Subutilização </a>
  
  * <a href="https://arthurwelle.github.io/REMIR/R.PNADCMensal_Posicao_Ocupacao1.html"> PNADC Mensal - Quantidade de ocupados por posição na ocupação </a>

  * <a href="https://arthurwelle.github.io/REMIR/R.PNADC_MapaDesempregoUF.html"> PNADC Trimestral - Mapa da taxa de desocupação por UF </a>
  
  * <a href="https://arthurwelle.github.io/REMIR/R.Rais_Qtd.html"> RAIS -  Quantidade de vínculos 31/12 </a>
  
  * <a href="https://arthurwelle.github.io/REMIR/R.Rais_Negativa.html"> RAIS Negativa, quantidade </a>  
  
  

### Formalização

  * <a href="https://arthurwelle.github.io/REMIR/R.PNADCT_Formalizacao1.html"> PNADC Trimestral - Taxa de formalização (Sexo, Idade, Região, Raça/Cor) </a> Proporção dentre os ocupados que são assalariados formais ou autônomos e empregadores com contribuição previdenciária.

  * <a href="https://arthurwelle.github.io/REMIR/R.PNADCT_TxLegalidade.html"> PNADC Trimestral - Taxa de legalidade (critério: Carteira e CNPJ) (Sexo, Idade, Região, Raça/Cor) </a> Proporção dentre os ocupados que são assalariados com carteira assinada ou empregadores e autônomos com cadastro de CNPJ.

  * <a href="https://arthurwelle.github.io/REMIR/R.PNADCT_InformalizacaoAdalberto.html"> Taxa de informalidade (Sexo, Idade, Região, Raça/Cor) </a> Proporção dentre os ocupados que são assalariados informais (sem carteira assinada), autônomos sem CNPJ, empregadores sem CNPJ com até um empregado e trabalhadores no auxílio familiar 

  * <a href="https://arthurwelle.github.io/REMIR/R.PNADCMensal_Contribuintes.html"> PNADC Mensal - Contribuição para a previdência </a>

  * <a href="https://arthurwelle.github.io/REMIR/R.PNADCMensal_Percentual_Contribuintes.html"> PNADC Mensal - Contribuição para a previdência (%) </a>
  
  * <a href="https://arthurwelle.github.io/REMIR/R.PNADCMensal_ContribuicaoVariacaoPosOcup.html"> PNADC Mensal - Contribuição para variação no total de ocupados por posição na ocupação </a>

 
  

### Formas de contratação

  * <a href="https://arthurwelle.github.io/REMIR/R.Caged_Adm_Intermitentes.html"> CAGED - Porcentagem de admitidos intermitentes </a> 
  
  * <a href="https://arthurwelle.github.io/REMIR/R.Caged_Adm_Parciais.html"> CAGED - Porcentagem de admitidos parciais </a> 

  * <a href="https://arthurwelle.github.io/REMIR/R.Caged_Adm_Intermitentes_Ocupacao.html"> CAGED - Prevalência de intermitentes por ocupação </a> 

  * <a href="https://arthurwelle.github.io/REMIR/R.RAIS_Intermitentes_CBO.html"> RAIS - Prevalência de intermitentes por ocupação </a> 






### Rendimentos

  * <a href="https://arthurwelle.github.io/REMIR/PNADCT_RendaMedia.html"> PNADC Trimestral - Renda média habitual real (Sexo, Idade, Região, Raça/Cor) </a> 
  
  * <a href="https://arthurwelle.github.io/REMIR/R.PNADCMensal_RendaMedia_TodosOsTrabalhos.html"> PNADC Mensal - Rendimento real médio habitual do todos os trabalhos </a>
  
  * <a href="https://arthurwelle.github.io/REMIR/R.PNADCMensal_RendaMedia_TrabalhoPrincipal.html"> PNADC Mensal - Rendimento real médio habitual do trabalhos principal </a>
    
  * <a href="https://arthurwelle.github.io/REMIR/R.PNADCMensal_Massa_Rendimento.html"> PNADC Mensal - Massa de rendimentos </a>
  
  * <a href="https://arthurwelle.github.io/REMIR/R.Caged_SalAdmDesl_Sexo.html"> CAGED - Salário real dos admitidos por sexo </a>
  
  
  
  
  
### Jornada
  
  * <a href="https://arthurwelle.github.io/REMIR/R.PNADC_HorasTrab.html"> PNADC Trimestral - Horas trabalhadas em todos os trabalhos </a> 
  
  
 
  

  
  <br/>
  <br/>
  <br/>
  
  
```{r}
    library(sf)
    library(geobr)
    library(ggplot2)
    library(gridExtra)

# Read all Brazilian states
    states <- geobr::read_state(code_state = 'all', year=2015)

# Select six states
    states6 <- subset(states, code_state %in% c(35,33,53,29,31,23))

# centroids, for refernece in the position of the map
    states6$centroid <- 
         sf::st_transform(states6, 29101) %>% 
         sf::st_centroid() %>% 
         sf::st_transform(., '+proj=longlat +ellps=GRS80 +no_defs')  %>% 
         sf::st_geometry()

# set padding
    padding <-7 

# function to make plots
    graph <- function(x){
      ggplot2::ggplot(states6[x,]) +
               geom_sf() +
               coord_sf(xlim = c(states6$centroid[[x]][1]-padding , 
                                 states6$centroid[[x]][1]+padding), 
                        ylim = c(states6$centroid[[x]][2]-padding , 
                                 states6$centroid[[x]][2]+padding), 
                        expand = FALSE)
    }

# create a bunch of plots
    
    g1 <- graph(1)
    g2 <- graph(2)
    g3 <- graph(3)
    g4 <- graph(4)
    g5 <- graph(5)
    g6 <- graph(6)

# grid them together
    g <- gridExtra::grid.arrange(g1, g2, g3, g4, g5, g6, ncol=3)
    g
    
```
  